## Importing libraries

In [7]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


from sklearn.ensemble import VotingClassifier
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn. preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from sklearn import preprocessing

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

### Loading dataset

In [11]:
data = pd.read_csv('dataset.csv')
data.head()

0   1   2  3  4   5  6  7    8  9  10  11
0  7  21  30  2  3  29  2  3   57  5   1   0
1  7  32  70  2  4  67  2  4  132  5   1   0
2  7  15   1  2  2   0  2  2    0  5   1   0
3  7  33  77  2  7  72  2  7  142  5   1   0
4  7  55  78  3  7  73  3  7  144  6   1   0

In [12]:
y = data.iloc[:,0].values
x = data.iloc[:,1:].values
x,y

(array([[  21,   30,    2, ...,    5,    1,    0],
        [  32,   70,    2, ...,    5,    1,    0],
        [  15,    1,    2, ...,    5,    1,    0],
        ...,
        [  82,   14,    7, ...,    1,    0,    1],
        [  30,   62,    2, ...,    3,    0,    0],
        [  30,   62,    2, ...,    7,    0, 9156]], dtype=int64),
 array([7, 7, 7, ..., 7, 7, 7], dtype=int64))

### Splitting the dataset into train and test

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x_mm,y)


### Scaling the dataset

In [17]:
mm = MinMaxScaler()
x_train_mm = mm.fit_transform(x_train)
x_test_mm = mm.transform(x_test)

In [18]:
x_train_mm,x_test_mm

(array([[8.07228916e-01, 4.31818182e-01, 5.71428571e-01, ...,
         7.00000000e-01, 1.00000000e+00, 3.09912289e-01],
        [3.97590361e-01, 8.75000000e-01, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 9.43129303e-05],
        [8.31325301e-01, 5.11363636e-01, 5.71428571e-01, ...,
         7.00000000e-01, 1.00000000e+00, 8.98707913e-01],
        ...,
        [4.21686747e-01, 9.65909091e-01, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 9.43129303e-05],
        [2.89156627e-01, 4.88636364e-01, 2.85714286e-01, ...,
         7.00000000e-01, 0.00000000e+00, 7.97698765e-01],
        [1.92771084e-01, 6.81818182e-02, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 0.00000000e+00]]),
 array([[8.55421687e-01, 5.79545455e-01, 5.71428571e-01, ...,
         3.00000000e-01, 0.00000000e+00, 0.00000000e+00],
        [1.80722892e-01, 1.13636364e-02, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 9.43129303e-05],
        [1.92771084e-01, 

## Defining models 

In [23]:
m1 = LogisticRegression(multi_class = 'multinomial', penalty = 'l2')
m2 = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski')
m3 = DecisionTreeClassifier()
m4 = RandomForestClassifier()
m5 = MultinomialNB()
m6 = LinearSVC()

In [ ]:
hybrid = []

In [ ]:
estimators = []

#Defining 5 Logistic Regression Models
model11 = LogisticRegression(penalty = 'l2', random_state = 0)
estimators.append(('logistic1', model11))
model12 = LogisticRegression(penalty = 'l2', random_state = 0)
estimators.append(('logistic2', model12))
model13 = LogisticRegression(penalty = 'l2', random_state = 0)
estimators.append(('logistic3', model13))
model14 = LogisticRegression(penalty = 'l2', random_state = 0)
estimators.append(('logistic4', model14))
model15 = LogisticRegression(penalty = 'l2', random_state = 0)
estimators.append(('logistic5', model15))

#Defining 5 Decision Tree Classifiers
model16 = DecisionTreeClassifier(max_depth = 3)
estimators.append(('cart1', model16))
model17 = DecisionTreeClassifier(max_depth = 4)
estimators.append(('cart2', model17))
model18 = DecisionTreeClassifier(max_depth = 5)
estimators.append(('cart3', model18))
model19 = DecisionTreeClassifier(max_depth = 2)
estimators.append(('cart4', model19))
model20 = DecisionTreeClassifier(max_depth = 3)
estimators.append(('cart5', model20))

#Defining 5 Support Vector Classifiers
# model21 = LinearSVC(kernel = 'linear')
# estimators.append(('svm1', model21))
# model22 = LinearSVC(kernel = 'poly')
# estimators.append(('svm2', model22))
# model23 = LinearSVC(kernel = 'rbf')
# estimators.append(('svm3', model23))
# model24 = LinearSVC(kernel = 'rbf')
# estimators.append(('svm4', model24))
# model25 = LinearSVC(kernel = 'linear')
# estimators.append(('svm5', model25))
model21 = LinearSVC()
estimators.append(('svm1', model21))
model22 = LinearSVC()
estimators.append(('svm2', model22))
model23 = LinearSVC()
estimators.append(('svm3', model23))
model24 = LinearSVC()
estimators.append(('svm4', model24))
model25 = LinearSVC()
estimators.append(('svm5', model25))

#Defining 5 K-NN classifiers
model26 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
estimators.append(('knn1', model26))
model27 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
estimators.append(('knn2', model27))
model28 = KNeighborsClassifier(n_neighbors = 6, metric = 'minkowski', p = 2)
estimators.append(('knn3', model28))
model29 = KNeighborsClassifier(n_neighbors = 4, metric = 'minkowski', p = 1)
estimators.append(('knn4', model29))
model30 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 1)
estimators.append(('knn5', model30))

#Defining 5 Naive Bayes classifiers
model31 = MultinomialNB()
estimators.append(('nbs1', model31))
model32 = MultinomialNB()
estimators.append(('nbs2', model32))
model33 = MultinomialNB()
estimators.append(('nbs3', model33))
model34 = MultinomialNB()
estimators.append(('nbs4', model34))
model35 = MultinomialNB()
estimators.append(('nbs5', model35))

# Defining the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(x_train, y_train)
y_pred = ensemble.predict(x_test)

#Confisuin matrix
cm_HybridEnsembler = confusion_matrix(y_test, y_pred)

c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st