## Importing Libraries

In [113]:
from time import time
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

### Loading dataset

In [114]:
data = pd.read_csv('dataset.csv')
data

Unnamed: 0  0   1   2  3   4   5  6   7    8  9  10    11
0                0  7  21  30  2   3  29  2   3   57  5   1     0
1                1  7  32  70  2   4  67  2   4  132  5   1     0
2                2  7  15   1  2   2   0  2   2    0  5   1     0
3                3  7  33  77  2   7  72  2   7  142  5   1     0
4                4  7  55  78  3   7  73  3   7  144  6   1     0
...            ... ..  ..  .. ..  ..  .. ..  ..  ... ..  ..   ...
355886      355886  7  25  46  2  15  45  4  15   90  7   0  8505
355887      355887  7  82  14  7  10   8  0  10   16  0   0    22
355888      355888  7  82  14  7  10   8  0  10   17  1   0     1
355889      355889  7  30  62  2  20  60  3  20  120  3   0     0
355890      355890  7  30  62  2  20  61  4  20  121  7   0  9156

[355891 rows x 13 columns]

### Data Preprocessing

In [115]:
data.drop(columns = "Unnamed: 0", inplace = True)
data.head()

0   1   2  3  4   5  6  7    8  9  10  11
0  7  21  30  2  3  29  2  3   57  5   1   0
1  7  32  70  2  4  67  2  4  132  5   1   0
2  7  15   1  2  2   0  2  2    0  5   1   0
3  7  33  77  2  7  72  2  7  142  5   1   0
4  7  55  78  3  7  73  3  7  144  6   1   0

In [116]:
y = data.iloc[:,0].values
x = data.iloc[:,1:].values
x,y

(array([[  21,   30,    2, ...,    5,    1,    0],
        [  32,   70,    2, ...,    5,    1,    0],
        [  15,    1,    2, ...,    5,    1,    0],
        ...,
        [  82,   14,    7, ...,    1,    0,    1],
        [  30,   62,    2, ...,    3,    0,    0],
        [  30,   62,    2, ...,    7,    0, 9156]], dtype=int64),
 array([7, 7, 7, ..., 7, 7, 7], dtype=int64))

### Splitting the dataset into training and testing 

In [117]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

### Scaling the dataset 

In [118]:
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

# Appliyng Machine Learning Algorithms

## Applying logistic regression

In [119]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [120]:
s = time()
lr.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)


Time elapsed 19.718257188796997


c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Training accuracy

In [121]:
lr.score(x_train_sc,y_train)

0.9889067054301321

### Testing accuracy

In [122]:
lr.score(x_test_sc,y_test)

0.989322603486451

### Accuracy of the model

In [123]:
y_lr_train_pred = lr.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_lr_train_pred)
print("Accuracy of Logistic Regression Training Dataset: ",accuracy)

Accuracy of Logistic Regression Training Dataset:  0.9889067054301321


In [124]:
y_lr_test_pred = lr.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_lr_test_pred)
print("Accuracy of Logistic Regression Testing Dataset: ",accuracy)

Accuracy of Logistic Regression Testing Dataset:  0.989322603486451


## Applying KNN

In [125]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [126]:
s = time()
knn.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 1.6394941806793213


### Training accuracy

In [127]:
knn.score(x_train_sc,y_train)

0.9934998763665246

### Testing accuracy

In [128]:
knn.score(x_test_sc,y_test)

0.9937621525631372

### Accuracy of the model

In [129]:
y_knn_train_pred = knn.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_knn_train_pred)
print("Accuracy of K Nearest Neigbour Training Dataset: ",accuracy)

Accuracy of K Nearest Neigbour Training Dataset:  0.9934998763665246


In [130]:
y_knn_test_pred = knn.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_knn_test_pred)
print("Accuracy of K Nearest Neigbour Testing Dataset: ",accuracy)

Accuracy of K Nearest Neigbour Testing Dataset:  0.9937621525631372


## Applying Decision Tree Classifier

In [131]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()

In [132]:
s = time()
dtc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 1.8935825824737549


### Training accuracy

In [133]:
dtc.score(x_train_sc,y_train)

0.9943465783499053

### Testing accuracy

In [134]:
dtc.score(x_test_sc,y_test)

0.9944589931777056

### Accuracy of the model

In [135]:
y_dtc_train_pred = dtc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_dtc_train_pred)
print("Accuracy of Decision Tree Classifier Training Dataset: ",accuracy)

Accuracy of Decision Tree Classifier Training Dataset:  0.9943465783499053


In [136]:
y_dtc_test_pred = dtc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_dtc_test_pred)
print("Accuracy of Decision Tree Classifier Testing Dataset: ",accuracy)

Accuracy of Decision Tree Classifier Testing Dataset:  0.9944589931777056


## Applying Random Forest Classifier

In [137]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [138]:
s = time()
rfc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 28.6869375705719


### Training accuracy

In [139]:
rfc.score(x_train_sc,y_train)

0.9943465783499053

### Testing accuracy

In [140]:
rfc.score(x_test_sc,y_test)

0.9944702325424567

### Accuracy of the model

In [141]:
y_rfc_train_pred = rfc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_rfc_train_pred)
print("Accuracy of Random Forest Classifier Training Dataset: ",accuracy)

Accuracy of Random Forest Classifier Training Dataset:  0.9943465783499053


In [142]:
y_rfc_test_pred = rfc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_rfc_test_pred)
print("Accuracy of Random Forest Classifier Testing Dataset: ",accuracy)

Accuracy of Random Forest Classifier Testing Dataset:  0.9944702325424567


## Applying Naive bayes 

In [143]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [144]:
s = time()
nb.fit(x_train,y_train)
print("Time elapsed",time()-s)

Time elapsed 0.13985347747802734


### Training accuracy

In [145]:
nb.score(x_train,y_train)

0.7536434410568039

### Testing accuracy

In [146]:
nb.score(x_test,y_test)

0.7547570611309049

### Accuracy of the model

In [147]:
y_nb_train_pred = nb.predict(x_train)
accuracy = accuracy_score(y_train,y_nb_train_pred)
print("Accuracy of Naive Bayes Training Dataset: ",accuracy)

Accuracy of Naive Bayes Training Dataset:  0.7536434410568039


In [148]:
y_nb_test_pred = nb.predict(x_test)
accuracy = accuracy_score(y_test,y_nb_test_pred)
print("Accuracy of Naive Bayes Testing Dataset: ",accuracy)

Accuracy of Naive Bayes Testing Dataset:  0.7547570611309049


## Applying SVM

In [149]:
from sklearn.svm import LinearSVC
svc = LinearSVC()

In [150]:
s = time()
svc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 91.46510314941406


### Training accuracy

In [151]:
svc.score(x_train_sc,y_train)

0.9838264935298481

### Testing accuracy

In [152]:
svc.score(x_test_sc,y_test)

0.9843098468074585

### Accuracy of the model

In [153]:
y_svc_train_pred = svc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_svc_train_pred)
print("Accuracy of Support Vector Machine Training Dataset: ",accuracy)

Accuracy of Support Vector Machine Training Dataset:  0.9838264935298481


In [154]:
y_svc_test_pred = svc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_svc_test_pred)
print("Accuracy of Support Vector Machine Testing Dataset: ",accuracy)

Accuracy of Support Vector Machine Testing Dataset:  0.9843098468074585


## Applying Artificial Neural Network using Tensorflow

In [181]:
import tensorflow as tf
from tensorflow.keras import Sequential,layers

In [182]:
y_train.shape,y_test.shape

((266918,), (88973,))

In [183]:
y_train = y_train.reshape(-1,1)

In [184]:
y_test = y_test.reshape(-1,1)

In [185]:
y_train.shape,y_test.shape

((266918, 1), (88973, 1))

In [186]:
x_train.shape,x_train_sc.shape,x_test.shape,x_test_sc.shape

((266918, 11), (266918, 11), (88973, 11), (88973, 11))

In [204]:
ann = Sequential([
    layers.Dense(10,input_shape=(11,),activation='relu'),
    layers.Dense(20,activation='relu'),
    layers.Dense(20,activation='relu'),
    layers.Dense(8,activation='sigmoid'),
    
])

ann.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])

ann.fit(x_train_sc,y_train,epochs= 20)

Epoch 1/20
8342/8342 [==============================] - 9s 999us/step - loss: 0.0550 - accuracy: 0.9858
Epoch 2/20
8342/8342 [==============================] - 14s 2ms/step - loss: 0.0163 - accuracy: 0.9929
Epoch 3/20
8342/8342 [==============================] - 14s 2ms/step - loss: 0.0126 - accuracy: 0.9940
Epoch 4/20
8342/8342 [==============================] - 15s 2ms/step - loss: 0.0119 - accuracy: 0.9941
Epoch 5/20
8342/8342 [==============================] - 16s 2ms/step - loss: 0.0118 - accuracy: 0.9942
Epoch 6/20
8342/8342 [==============================] - 22s 3ms/step - loss: 0.0116 - accuracy: 0.9942
Epoch 7/20
8342/8342 [==============================] - 20s 2ms/step - loss: 0.0116 - accuracy: 0.9943
Epoch 8/20
8342/8342 [==============================] - 18s 2ms/step - loss: 0.0113 - accuracy: 0.9943
Epoch 9/20
8342/8342 [==============================] - 18s 2ms/step - loss: 0.0115 - accuracy: 0.9942
Epoch 10/20
8342/8342 [==============================] - 16s 2ms/step - 

### Training Accuracy

In [212]:
loss_train, acc_train = ann.evaluate(x_train_sc,y_train)
acc_train

8342/8342 [==============================] - 5s 543us/step - loss: 0.0110 - accuracy: 0.9943


0.9943353533744812

### Testing Accuracy

In [211]:
loss_test, acc_test = ann.evaluate(x_test_sc,y_test)
acc_test

2781/2781 [==============================] - 2s 552us/step - loss: 0.0110 - accuracy: 0.9944


0.9944028258323669

## Evaluation Metrics

In [155]:
target_names = ['Normal', 'DoSattack', 'scan', 'malitiousControl', 'malitiousOperation', 'spying', 'dataProbing', 'wrongSetUp']

In [156]:
target_names

['Normal',
 'DoSattack',
 'scan',
 'malitiousControl',
 'malitiousOperation',
 'spying',
 'dataProbing',
 'wrongSetUp']

## Classification Report of Logistic Regression

### For Training Dataset

In [157]:
print(classification_report(y_train, y_lr_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.94      0.50      0.65      3020
         DoSattack       1.00      0.82      0.90       189
              scan       0.97      0.91      0.94       680
  malitiousControl       0.84      0.75      0.79       493
malitiousOperation       0.84      0.49      0.62      1153
            spying       0.00      0.00      0.00       401
       dataProbing       0.91      1.00      0.95        96
        wrongSetUp       0.99      1.00      0.99    260886

          accuracy                           0.99    266918
         macro avg       0.81      0.68      0.73    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [158]:
print(classification_report(y_test, y_lr_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.94      0.50      0.65       980
         DoSattack       1.00      0.85      0.92        53
              scan       0.99      0.96      0.97       209
  malitiousControl       0.85      0.69      0.76       164
malitiousOperation       0.87      0.49      0.63       378
            spying       0.00      0.00      0.00       131
       dataProbing       0.96      1.00      0.98        26
        wrongSetUp       0.99      1.00      0.99     87032

          accuracy                           0.99     88973
         macro avg       0.82      0.69      0.74     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Logistic Regression

### For Training dataset

In [159]:
confusion_matrix(y_train, y_lr_train_pred)

array([[  1511,      0,      0,      0,      0,      0,      0,   1509],
       [     0,    155,      0,      0,      0,      0,      0,     34],
       [     0,      0,    620,      0,     33,      0,      0,     27],
       [     0,      0,      0,    370,      0,      0,      0,    123],
       [     7,      0,     18,      0,    565,      0,     10,    553],
       [     0,      0,      0,      0,     51,      0,      0,    350],
       [     0,      0,      0,      0,      0,      0,     96,      0],
       [    88,      0,      2,     73,     22,     61,      0, 260640]],
      dtype=int64)

### For Testing dataset

In [160]:
confusion_matrix(y_test, y_lr_test_pred)

array([[  489,     0,     0,     0,     0,     0,     0,   491],
       [    0,    45,     0,     0,     0,     0,     0,     8],
       [    0,     0,   200,     0,     5,     0,     0,     4],
       [    0,     0,     0,   113,     0,     0,     0,    51],
       [    4,     0,     2,     0,   186,     0,     1,   185],
       [    0,     0,     0,     0,    19,     0,     0,   112],
       [    0,     0,     0,     0,     0,     0,    26,     0],
       [   27,     0,     1,    20,     4,    16,     0, 86964]],
      dtype=int64)

## Classification Report for K Nearest Neighbour

### For Training Dataset

In [161]:
print(classification_report(y_train, y_knn_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.64      1.00      0.78      3020
         DoSattack       1.00      1.00      1.00       189
              scan       1.00      1.00      1.00       680
  malitiousControl       1.00      1.00      1.00       493
malitiousOperation       1.00      1.00      1.00      1153
            spying       1.00      1.00      1.00       401
       dataProbing       1.00      1.00      1.00        96
        wrongSetUp       1.00      0.99      1.00    260886

          accuracy                           0.99    266918
         macro avg       0.95      1.00      0.97    266918
      weighted avg       1.00      0.99      0.99    266918



### For Testing Dataset

In [162]:
print(classification_report(y_test, y_knn_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.64      1.00      0.78       980
         DoSattack       1.00      1.00      1.00        53
              scan       1.00      1.00      1.00       209
  malitiousControl       1.00      1.00      1.00       164
malitiousOperation       1.00      1.00      1.00       378
            spying       1.00      1.00      1.00       131
       dataProbing       1.00      1.00      1.00        26
        wrongSetUp       1.00      0.99      1.00     87032

          accuracy                           0.99     88973
         macro avg       0.95      1.00      0.97     88973
      weighted avg       1.00      0.99      0.99     88973



## Confusion Matrix for K Nearest Neighbour

### For Training dataset

In [163]:
confusion_matrix(y_train, y_knn_train_pred)

array([[  3020,      0,      0,      0,      0,      0,      0,      0],
       [     0,    189,      0,      0,      0,      0,      0,      0],
       [     0,      0,    680,      0,      0,      0,      0,      0],
       [     0,      0,      0,    493,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1153,      0,      0,      0],
       [     0,      0,      0,      0,      0,    401,      0,      0],
       [     0,      0,      0,      0,      0,      0,     96,      0],
       [  1731,      0,      0,      0,      3,      1,      0, 259151]],
      dtype=int64)

### For Testing dataset

In [164]:
confusion_matrix(y_test, y_knn_test_pred)

array([[  980,     0,     0,     0,     0,     0,     0,     0],
       [    0,    53,     0,     0,     0,     0,     0,     0],
       [    0,     0,   209,     0,     0,     0,     0,     0],
       [    0,     0,     0,   164,     0,     0,     0,     0],
       [    0,     0,     0,     0,   378,     0,     0,     0],
       [    0,     0,     0,     0,     0,   131,     0,     0],
       [    0,     0,     0,     0,     0,     0,    26,     0],
       [  554,     0,     0,     0,     1,     0,     0, 86477]],
      dtype=int64)

## Classification Report for Decision Tree Classifier

### For Training Dataset

In [165]:
print(classification_report(y_train, y_dtc_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67      3020
         DoSattack       1.00      1.00      1.00       189
              scan       1.00      1.00      1.00       680
  malitiousControl       1.00      1.00      1.00       493
malitiousOperation       1.00      1.00      1.00      1153
            spying       1.00      1.00      1.00       401
       dataProbing       1.00      1.00      1.00        96
        wrongSetUp       0.99      1.00      1.00    260886

          accuracy                           0.99    266918
         macro avg       1.00      0.94      0.96    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [166]:
print(classification_report(y_test, y_dtc_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67       980
         DoSattack       1.00      1.00      1.00        53
              scan       1.00      1.00      1.00       209
  malitiousControl       1.00      1.00      1.00       164
malitiousOperation       1.00      1.00      1.00       378
            spying       0.99      1.00      1.00       131
       dataProbing       1.00      1.00      1.00        26
        wrongSetUp       0.99      1.00      1.00     87032

          accuracy                           0.99     88973
         macro avg       1.00      0.94      0.96     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Decision Tree Classifier

### For Training dataset

In [167]:
confusion_matrix(y_train, y_dtc_train_pred)

array([[  1511,      0,      0,      0,      0,      0,      0,   1509],
       [     0,    189,      0,      0,      0,      0,      0,      0],
       [     0,      0,    680,      0,      0,      0,      0,      0],
       [     0,      0,      0,    493,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1153,      0,      0,      0],
       [     0,      0,      0,      0,      0,    401,      0,      0],
       [     0,      0,      0,      0,      0,      0,     96,      0],
       [     0,      0,      0,      0,      0,      0,      0, 260886]],
      dtype=int64)

### For Testing dataset

In [168]:
confusion_matrix(y_test, y_dtc_test_pred)

array([[  489,     0,     0,     0,     0,     0,     0,   491],
       [    0,    53,     0,     0,     0,     0,     0,     0],
       [    0,     0,   209,     0,     0,     0,     0,     0],
       [    0,     0,     0,   164,     0,     0,     0,     0],
       [    0,     0,     0,     0,   378,     0,     0,     0],
       [    0,     0,     0,     0,     0,   131,     0,     0],
       [    0,     0,     0,     0,     0,     0,    26,     0],
       [    1,     0,     0,     0,     0,     1,     0, 87030]],
      dtype=int64)

## Classification Report for Random Forest Classifier

### For Training Dataset

In [169]:
print(classification_report(y_train, y_rfc_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67      3020
         DoSattack       1.00      1.00      1.00       189
              scan       1.00      1.00      1.00       680
  malitiousControl       1.00      1.00      1.00       493
malitiousOperation       1.00      1.00      1.00      1153
            spying       1.00      1.00      1.00       401
       dataProbing       1.00      1.00      1.00        96
        wrongSetUp       0.99      1.00      1.00    260886

          accuracy                           0.99    266918
         macro avg       1.00      0.94      0.96    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [170]:
print(classification_report(y_test, y_rfc_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67       980
         DoSattack       1.00      1.00      1.00        53
              scan       1.00      1.00      1.00       209
  malitiousControl       1.00      1.00      1.00       164
malitiousOperation       1.00      1.00      1.00       378
            spying       1.00      1.00      1.00       131
       dataProbing       1.00      1.00      1.00        26
        wrongSetUp       0.99      1.00      1.00     87032

          accuracy                           0.99     88973
         macro avg       1.00      0.94      0.96     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Random Forest Classifier

### For Training dataset

In [171]:
confusion_matrix(y_train, y_rfc_train_pred)

array([[  1511,      0,      0,      0,      0,      0,      0,   1509],
       [     0,    189,      0,      0,      0,      0,      0,      0],
       [     0,      0,    680,      0,      0,      0,      0,      0],
       [     0,      0,      0,    493,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1153,      0,      0,      0],
       [     0,      0,      0,      0,      0,    401,      0,      0],
       [     0,      0,      0,      0,      0,      0,     96,      0],
       [     0,      0,      0,      0,      0,      0,      0, 260886]],
      dtype=int64)

### For Testing dataset

In [172]:
confusion_matrix(y_test, y_rfc_test_pred)

array([[  489,     0,     0,     0,     0,     0,     0,   491],
       [    0,    53,     0,     0,     0,     0,     0,     0],
       [    0,     0,   209,     0,     0,     0,     0,     0],
       [    0,     0,     0,   164,     0,     0,     0,     0],
       [    0,     0,     0,     0,   378,     0,     0,     0],
       [    0,     0,     0,     0,     0,   131,     0,     0],
       [    0,     0,     0,     0,     0,     0,    26,     0],
       [    1,     0,     0,     0,     0,     0,     0, 87031]],
      dtype=int64)

## Classification Report for Naive Bayes

### For Training Dataset

In [173]:
print(classification_report(y_train, y_nb_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.29      1.00      0.45      3020
         DoSattack       0.04      0.82      0.07       189
              scan       0.18      0.91      0.30       680
  malitiousControl       0.66      1.00      0.80       493
malitiousOperation       1.00      0.14      0.24      1153
            spying       0.01      0.94      0.01       401
       dataProbing       1.00      1.00      1.00        96
        wrongSetUp       1.00      0.75      0.86    260886

          accuracy                           0.75    266918
         macro avg       0.52      0.82      0.47    266918
      weighted avg       0.98      0.75      0.85    266918



### For Testing Dataset

In [174]:
print(classification_report(y_test, y_nb_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.28      1.00      0.44       980
         DoSattack       0.04      0.85      0.07        53
              scan       0.18      0.96      0.31       209
  malitiousControl       0.67      1.00      0.80       164
malitiousOperation       1.00      0.14      0.25       378
            spying       0.01      0.92      0.01       131
       dataProbing       1.00      1.00      1.00        26
        wrongSetUp       1.00      0.75      0.86     87032

          accuracy                           0.75     88973
         macro avg       0.52      0.83      0.47     88973
      weighted avg       0.99      0.75      0.85     88973



## Confusion Matrix for Naive Bayes

### For Training dataset

In [175]:
confusion_matrix(y_train, y_nb_train_pred)

array([[  3020,      0,      0,      0,      0,      0,      0,      0],
       [     0,    155,      0,      0,      0,      0,      0,     34],
       [     0,      0,    620,      0,      0,      8,      0,     52],
       [     0,      0,      0,    493,      0,      0,      0,      0],
       [     6,      0,      0,      0,    156,    631,      0,    360],
       [     0,      0,     24,      0,      0,    377,      0,      0],
       [     0,      0,      0,      0,      0,      0,     96,      0],
       [  7466,   3893,   2840,    252,      0,  50191,      0, 196244]],
      dtype=int64)

### For Testing dataset

In [176]:
confusion_matrix(y_test, y_nb_test_pred)

array([[  980,     0,     0,     0,     0,     0,     0,     0],
       [    0,    45,     0,     0,     0,     0,     0,     8],
       [    0,     0,   200,     0,     0,     1,     0,     8],
       [    0,     0,     0,   164,     0,     0,     0,     0],
       [    5,     0,     0,     0,    54,   201,     0,   118],
       [    0,     0,    11,     0,     0,   120,     0,     0],
       [    0,     0,     0,     0,     0,     0,    26,     0],
       [ 2496,  1233,   881,    80,     0, 16778,     0, 65564]],
      dtype=int64)

## Classification Report for Support Vector Machine Classifier

### For Training Dataset

In [177]:
print(classification_report(y_train, y_svc_train_pred, target_names=target_names))

c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                    precision    recall  f1-score   support

            Normal       0.95      0.50      0.66      3020
         DoSattack       0.00      0.00      0.00       189
              scan       0.00      0.00      0.00       680
  malitiousControl       0.99      0.60      0.75       493
malitiousOperation       0.00      0.00      0.00      1153
            spying       0.00      0.00      0.00       401
       dataProbing       0.00      0.00      0.00        96
        wrongSetUp       0.98      1.00      0.99    260886

          accuracy                           0.98    266918
         macro avg       0.37      0.26      0.30    266918
      weighted avg       0.97      0.98      0.98    266918



c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### For Testing Dataset

In [178]:
print(classification_report(y_test, y_svc_test_pred, target_names=target_names))

c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                    precision    recall  f1-score   support

            Normal       0.94      0.50      0.65       980
         DoSattack       0.00      0.00      0.00        53
              scan       0.00      0.00      0.00       209
  malitiousControl       0.99      0.55      0.71       164
malitiousOperation       0.00      0.00      0.00       378
            spying       0.00      0.00      0.00       131
       dataProbing       0.00      0.00      0.00        26
        wrongSetUp       0.98      1.00      0.99     87032

          accuracy                           0.98     88973
         macro avg       0.36      0.26      0.29     88973
      weighted avg       0.98      0.98      0.98     88973



c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Confusion Matrix for Support Vector Machine Classifier

### For Training dataset

In [179]:
confusion_matrix(y_train, y_svc_train_pred)

array([[  1511,      0,      0,      0,      0,      0,      0,   1509],
       [     0,      0,      0,      0,      0,      0,      0,    189],
       [     0,      0,      0,      0,      0,      0,      0,    680],
       [     0,      0,      0,    296,      0,      0,      0,    197],
       [     7,      0,     10,      0,      0,      0,      0,   1136],
       [     0,      0,      0,      0,      0,      0,      0,    401],
       [     0,      0,      0,      0,      0,      0,      0,     96],
       [    75,      0,      0,      2,      0,     15,      0, 260794]],
      dtype=int64)

### For Testing dataset

In [180]:
confusion_matrix(y_test, y_svc_test_pred)

array([[  489,     0,     0,     0,     0,     0,     0,   491],
       [    0,     0,     0,     0,     0,     0,     0,    53],
       [    0,     0,     0,     0,     0,     0,     0,   209],
       [    0,     0,     0,    91,     0,     0,     0,    73],
       [    4,     0,     0,     0,     0,     0,     0,   374],
       [    0,     0,     0,     0,     0,     0,     0,   131],
       [    0,     0,     0,     0,     0,     0,     0,    26],
       [   28,     0,     0,     1,     0,     6,     0, 86997]],
      dtype=int64)

## Confusion Matrix for Artificial Neural Network

### For Training dataset

In [190]:
y_train_pred = ann.predict(x_train_sc)
y_train_pred

array([[1.0065258e-02, 2.3542063e-10, 1.6500109e-06, ..., 2.1263957e-03,
        1.3301840e-06, 9.8969066e-01],
       [1.7115951e-23, 9.7421541e-12, 1.3171141e-17, ..., 4.4153854e-13,
        8.0803141e-32, 9.9999553e-01],
       [1.0962601e-21, 2.8020392e-12, 6.9995789e-12, ..., 3.1447013e-07,
        5.6145255e-30, 9.9026966e-01],
       ...,
       [0.0000000e+00, 0.0000000e+00, 1.3360381e-04, ..., 4.3092929e-05,
        0.0000000e+00, 9.9779373e-01],
       [1.1914322e-14, 6.3162009e-09, 5.1703768e-07, ..., 7.3741496e-02,
        1.1053640e-21, 9.9651551e-01],
       [9.1343173e-18, 4.9642229e-15, 1.5210404e-13, ..., 1.7474068e-06,
        6.2163302e-21, 9.9997675e-01]], dtype=float32)

In [191]:
y_train.shape

(266918, 1)

In [192]:
y_train_pred.shape

(266918, 8)

In [193]:
y_train_pred_labels = [np.argmax(i) for i in y_train_pred]
y_train_pred_labels[:5]

[7, 7, 7, 7, 7]

In [194]:
print(tf.math.confusion_matrix(labels=y_train, predictions=y_train_pred_labels))

tf.Tensor(
[[  1511      0      0      0      0      0      0   1509]
 [     0    189      0      0      0      0      0      0]
 [     0      0    680      0      0      0      0      0]
 [     0      0      0    493      0      0      0      0]
 [     0      0      0      0   1074      0      0     79]
 [     0      0      0      0      0    401      0      0]
 [     0      0      0      0      0      0     96      0]
 [     7      0      3      0      1      0      1 260874]], shape=(8, 8), dtype=int32)


### For Testing dataset

In [195]:
y_test_pred = ann.predict(x_test_sc)
y_test_pred

array([[4.0492180e-14, 6.8113673e-14, 4.6870695e-11, ..., 2.2610385e-08,
        2.4549512e-20, 9.8912942e-01],
       [1.3766658e-14, 5.3092718e-11, 4.5644604e-09, ..., 1.2832880e-04,
        4.6689622e-20, 8.8549620e-01],
       [0.0000000e+00, 1.8185896e-10, 3.8752865e-27, ..., 4.1960167e-37,
        0.0000000e+00, 8.8671476e-01],
       ...,
       [0.0000000e+00, 3.3195949e-05, 4.9101464e-17, ..., 6.0407126e-13,
        0.0000000e+00, 9.9909174e-01],
       [2.9050651e-15, 3.6726361e-10, 6.0251942e-08, ..., 4.1555673e-02,
        3.0527718e-24, 9.9849951e-01],
       [1.3422627e-16, 1.3535068e-10, 1.5520317e-09, ..., 2.1308661e-03,
        2.3971970e-26, 9.9969965e-01]], dtype=float32)

In [196]:
y_test.shape

(88973, 1)

In [197]:
y_test_pred.shape

(88973, 8)

In [199]:
y_test_pred_labels = [np.argmax(i) for i in y_test_pred]
y_test_pred_labels[:5]

[7, 7, 7, 7, 7]

In [201]:
print(tf.math.confusion_matrix(labels=y_test, predictions=y_test_pred_labels))

tf.Tensor(
[[  489     0     0     0     0     0     0   491]
 [    0    53     0     0     0     0     0     0]
 [    0     0   209     0     0     0     0     0]
 [    0     0     0   164     0     0     0     0]
 [    0     0     0     0   343     0     0    35]
 [    0     0     0     0     0   131     0     0]
 [    0     0     0     0     0     0    26     0]
 [    6     0     1     0     3     0     0 87022]], shape=(8, 8), dtype=int32)


## Classification Report for Artificial Neural Network

### For Training dataset

In [209]:
print(classification_report(y_train, y_train_pred_labels, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67      3020
         DoSattack       1.00      1.00      1.00       189
              scan       1.00      1.00      1.00       680
  malitiousControl       1.00      1.00      1.00       493
malitiousOperation       1.00      0.93      0.96      1153
            spying       1.00      1.00      1.00       401
       dataProbing       0.99      1.00      0.99        96
        wrongSetUp       0.99      1.00      1.00    260886

          accuracy                           0.99    266918
         macro avg       1.00      0.93      0.95    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing dataset

In [208]:
print(classification_report(y_test, y_test_pred_labels, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.99      0.50      0.66       980
         DoSattack       1.00      1.00      1.00        53
              scan       1.00      1.00      1.00       209
  malitiousControl       1.00      1.00      1.00       164
malitiousOperation       0.99      0.91      0.95       378
            spying       1.00      1.00      1.00       131
       dataProbing       1.00      1.00      1.00        26
        wrongSetUp       0.99      1.00      1.00     87032

          accuracy                           0.99     88973
         macro avg       1.00      0.93      0.95     88973
      weighted avg       0.99      0.99      0.99     88973

