## Importing Libraries

In [36]:
from time import time
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

### Loading dataset

In [2]:
data = pd.read_csv('dataset.csv')
data

Unnamed: 0  0   1   2  3   4   5  6   7    8  9  10    11
0                0  7  21  30  2   3  29  2   3   57  5   1     0
1                1  7  32  70  2   4  67  2   4  132  5   1     0
2                2  7  15   1  2   2   0  2   2    0  5   1     0
3                3  7  33  77  2   7  72  2   7  142  5   1     0
4                4  7  55  78  3   7  73  3   7  144  6   1     0
...            ... ..  ..  .. ..  ..  .. ..  ..  ... ..  ..   ...
355886      355886  7  25  46  2  15  45  4  15   90  7   0  8505
355887      355887  7  82  14  7  10   8  0  10   16  0   0    22
355888      355888  7  82  14  7  10   8  0  10   17  1   0     1
355889      355889  7  30  62  2  20  60  3  20  120  3   0     0
355890      355890  7  30  62  2  20  61  4  20  121  7   0  9156

[355891 rows x 13 columns]

### Data Preprocessing

In [3]:
data.drop(columns = "Unnamed: 0", inplace = True)
data.head()

0   1   2  3  4   5  6  7    8  9  10  11
0  7  21  30  2  3  29  2  3   57  5   1   0
1  7  32  70  2  4  67  2  4  132  5   1   0
2  7  15   1  2  2   0  2  2    0  5   1   0
3  7  33  77  2  7  72  2  7  142  5   1   0
4  7  55  78  3  7  73  3  7  144  6   1   0

In [4]:
y = data.iloc[:,0].values
x = data.iloc[:,1:].values
x,y

(array([[  21,   30,    2, ...,    5,    1,    0],
        [  32,   70,    2, ...,    5,    1,    0],
        [  15,    1,    2, ...,    5,    1,    0],
        ...,
        [  82,   14,    7, ...,    1,    0,    1],
        [  30,   62,    2, ...,    3,    0,    0],
        [  30,   62,    2, ...,    7,    0, 9156]], dtype=int64),
 array([7, 7, 7, ..., 7, 7, 7], dtype=int64))

### Splitting the dataset into training and testing 

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

### Scaling the dataset 

In [6]:
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

# Appliyng Machine Learning Algorithms

## Applying logistic regression

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [8]:
s = time()
lr.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)


Time elapsed 20.73866844177246


c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Training accuracy

In [9]:
lr.score(x_train_sc,y_train)

0.9889591559954742

### Testing accuracy

In [10]:
lr.score(x_test_sc,y_test)

0.9888505501669046

### Accuracy of the model

In [60]:
y_lr_train_pred = lr.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_lr_train_pred)
print("Accuracy of Logistic Regression Training Dataset: ",accuracy)

Accuracy of Logistic Regression Training Dataset:  0.9889591559954742


In [61]:
y_lr_test_pred = lr.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_lr_test_pred)
print("Accuracy of Logistic Regression Testing Dataset: ",accuracy)

Accuracy of Logistic Regression Testing Dataset:  0.9888505501669046


## Applying KNN

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [12]:
s = time()
knn.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 1.931051254272461


### Training accuracy

In [13]:
knn.score(x_train_sc,y_train)

0.9934961298975715

### Testing accuracy

In [14]:
knn.score(x_test_sc,y_test)

0.9937846312926394

### Accuracy of the model

In [62]:
y_knn_train_pred = knn.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_knn_train_pred)
print("Accuracy of K Nearest Neigbour Training Dataset: ",accuracy)

Accuracy of K Nearest Neigbour Training Dataset:  0.9934961298975715


In [63]:
y_knn_test_pred = knn.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_knn_test_pred)
print("Accuracy of K Nearest Neigbour Testing Dataset: ",accuracy)

Accuracy of K Nearest Neigbour Testing Dataset:  0.9937846312926394


## Applying Decision Tree Classifier

In [15]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()

In [16]:
s = time()
dtc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 1.2057952880859375


### Training accuracy

In [17]:
dtc.score(x_train_sc,y_train)

0.9944814512322137

### Testing accuracy

In [18]:
dtc.score(x_test_sc,y_test)

0.994076854776168

### Accuracy of the model

In [64]:
y_dtc_train_pred = dtc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_dtc_train_pred)
print("Accuracy of Decision Tree Classifier Training Dataset: ",accuracy)

Accuracy of Decision Tree Classifier Training Dataset:  0.9944814512322137


In [66]:
y_dtc_test_pred = dtc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_dtc_test_pred)
print("Accuracy of Decision Tree Classifier Testing Dataset: ",accuracy)

Accuracy of Decision Tree Classifier Testing Dataset:  0.994076854776168


## Applying Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [20]:
s = time()
rfc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 32.81076097488403


### Training accuracy

In [21]:
rfc.score(x_train_sc,y_train)

0.9944814512322137

### Testing accuracy

In [22]:
rfc.score(x_test_sc,y_test)

0.994076854776168

### Accuracy of the model

In [67]:
y_rfc_train_pred = rfc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_rfc_train_pred)
print("Accuracy of Random Forest Classifier Training Dataset: ",accuracy)

Accuracy of Random Forest Classifier Training Dataset:  0.9944814512322137


In [68]:
y_rfc_test_pred = rfc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_rfc_test_pred)
print("Accuracy of Random Forest Classifier Testing Dataset: ",accuracy)

Accuracy of Random Forest Classifier Testing Dataset:  0.994076854776168


## Applying Naive bayes 

In [23]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [24]:
s = time()
nb.fit(x_train,y_train)
print("Time elapsed",time()-s)

Time elapsed 0.20797514915466309


### Training accuracy

In [25]:
nb.score(x_train,y_train)

0.7526768520669269

### Testing accuracy

In [26]:
nb.score(x_test,y_test)

0.7529587627707282

### Accuracy of the model

In [69]:
y_nb_train_pred = nb.predict(x_train)
accuracy = accuracy_score(y_train,y_nb_train_pred)
print("Accuracy of Naive Bayes Training Dataset: ",accuracy)

Accuracy of Naive Bayes Training Dataset:  0.7526768520669269


In [70]:
y_nb_test_pred = nb.predict(x_test)
accuracy = accuracy_score(y_test,y_nb_test_pred)
print("Accuracy of Naive Bayes Testing Dataset: ",accuracy)

Accuracy of Naive Bayes Testing Dataset:  0.7529587627707282


## Applying SVM

In [27]:
from sklearn.svm import LinearSVC
svc = LinearSVC()

In [28]:
s = time()
svc.fit(x_train_sc,y_train)
print("Time elapsed",time()-s)

Time elapsed 76.34469270706177


### Training accuracy

In [29]:
svc.score(x_train_sc,y_train)

0.9842535909904915

### Testing accuracy

In [30]:
svc.score(x_test_sc,y_test)

0.9841749744304452

### Accuracy of the model

In [72]:
y_svc_train_pred = svc.predict(x_train_sc)
accuracy = accuracy_score(y_train,y_svc_train_pred)
print("Accuracy of Support Vector Machine Training Dataset: ",accuracy)

Accuracy of Support Vector Machine Training Dataset:  0.9842535909904915


In [73]:
y_svc_test_pred = svc.predict(x_test_sc)
accuracy = accuracy_score(y_test,y_svc_test_pred)
print("Accuracy of Support Vector Machine Testing Dataset: ",accuracy)

Accuracy of Support Vector Machine Testing Dataset:  0.9841749744304452


## Evaluation Metrics

In [74]:
target_names = ['Normal', 'DoSattack', 'scan', 'malitiousControl', 'malitiousOperation', 'spying', 'dataProbing', 'wrongSetUp']

In [75]:
target_names

['Normal',
 'DoSattack',
 'scan',
 'malitiousControl',
 'malitiousOperation',
 'spying',
 'dataProbing',
 'wrongSetUp']

## Logistic Regression

### For Training Dataset

In [77]:
print(classification_report(y_train, y_lr_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.94      0.50      0.66      2963
         DoSattack       1.00      0.84      0.91       179
              scan       0.98      0.93      0.95       671
  malitiousControl       0.84      0.73      0.78       501
malitiousOperation       0.87      0.46      0.60      1150
            spying       0.00      0.00      0.00       398
       dataProbing       0.92      1.00      0.96       101
        wrongSetUp       0.99      1.00      0.99    260955

          accuracy                           0.99    266918
         macro avg       0.82      0.68      0.73    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [78]:
print(classification_report(y_test, y_lr_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.96      0.49      0.65      1037
         DoSattack       1.00      0.79      0.88        63
              scan       0.99      0.91      0.95       218
  malitiousControl       0.83      0.74      0.78       156
malitiousOperation       0.89      0.50      0.64       381
            spying       0.00      0.00      0.00       134
       dataProbing       0.91      1.00      0.95        21
        wrongSetUp       0.99      1.00      0.99     86963

          accuracy                           0.99     88973
         macro avg       0.82      0.68      0.73     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Logistic Regression

### For Training dataset

In [82]:
confusion_matrix(y_train, y_lr_train_pred)

array([[  1490,      0,      0,      0,      0,      0,      0,   1473],
       [     0,    150,      0,      0,      0,      0,      0,     29],
       [     0,      0,    622,      0,     28,      0,      0,     21],
       [     0,      0,      0,    367,      0,      0,      0,    134],
       [     0,      0,      9,      0,    529,      0,      9,    603],
       [     0,      0,      0,      0,     27,      0,      0,    371],
       [     0,      0,      0,      0,      0,      0,    101,      0],
       [    92,      0,      3,     68,     24,     56,      0, 260712]],
      dtype=int64)

### For Testing dataset

In [81]:
confusion_matrix(y_test, y_lr_test_pred)

array([[  510,     0,     0,     0,     0,     0,     0,   527],
       [    0,    50,     0,     0,     0,     0,     0,    13],
       [    0,     0,   198,     0,    10,     0,     0,    10],
       [    0,     0,     0,   116,     0,     0,     0,    40],
       [    0,     0,     1,     0,   190,     0,     2,   188],
       [    0,     0,     0,     0,     8,     0,     0,   126],
       [    0,     0,     0,     0,     0,     0,    21,     0],
       [   22,     0,     0,    24,     6,    15,     0, 86896]],
      dtype=int64)

## K Nearest Neigbour

### For Training Dataset

In [79]:
print(classification_report(y_train, y_knn_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.63      1.00      0.77      2963
         DoSattack       1.00      1.00      1.00       179
              scan       1.00      1.00      1.00       671
  malitiousControl       1.00      1.00      1.00       501
malitiousOperation       1.00      1.00      1.00      1150
            spying       1.00      1.00      1.00       398
       dataProbing       1.00      1.00      1.00       101
        wrongSetUp       1.00      0.99      1.00    260955

          accuracy                           0.99    266918
         macro avg       0.95      1.00      0.97    266918
      weighted avg       1.00      0.99      0.99    266918



### For Testing Dataset

In [80]:
print(classification_report(y_test, y_knn_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.65      1.00      0.79      1037
         DoSattack       1.00      1.00      1.00        63
              scan       1.00      1.00      1.00       218
  malitiousControl       1.00      1.00      1.00       156
malitiousOperation       1.00      1.00      1.00       381
            spying       1.00      1.00      1.00       134
       dataProbing       1.00      1.00      1.00        21
        wrongSetUp       1.00      0.99      1.00     86963

          accuracy                           0.99     88973
         macro avg       0.96      1.00      0.97     88973
      weighted avg       1.00      0.99      0.99     88973



## Confusion Matrix for K Nearest Neigbour

### For Training dataset

In [83]:
confusion_matrix(y_train, y_knn_train_pred)

array([[  2963,      0,      0,      0,      0,      0,      0,      0],
       [     0,    179,      0,      0,      0,      0,      0,      0],
       [     0,      0,    671,      0,      0,      0,      0,      0],
       [     0,      0,      0,    501,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1150,      0,      0,      0],
       [     0,      0,      0,      0,      0,    398,      0,      0],
       [     0,      0,      0,      0,      0,      0,    101,      0],
       [  1732,      0,      0,      0,      3,      1,      0, 259219]],
      dtype=int64)

### For Testing dataset

In [84]:
confusion_matrix(y_test, y_knn_test_pred)

array([[ 1037,     0,     0,     0,     0,     0,     0,     0],
       [    0,    63,     0,     0,     0,     0,     0,     0],
       [    0,     0,   218,     0,     0,     0,     0,     0],
       [    0,     0,     0,   156,     0,     0,     0,     0],
       [    0,     0,     0,     0,   381,     0,     0,     0],
       [    0,     0,     0,     0,     0,   134,     0,     0],
       [    0,     0,     0,     0,     0,     0,    21,     0],
       [  552,     0,     0,     0,     1,     0,     0, 86410]],
      dtype=int64)

## Decision Tree Classifier

### For Training Dataset

In [85]:
print(classification_report(y_train, y_dtc_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67      2963
         DoSattack       1.00      1.00      1.00       179
              scan       1.00      1.00      1.00       671
  malitiousControl       1.00      1.00      1.00       501
malitiousOperation       1.00      1.00      1.00      1150
            spying       1.00      1.00      1.00       398
       dataProbing       1.00      1.00      1.00       101
        wrongSetUp       0.99      1.00      1.00    260955

          accuracy                           0.99    266918
         macro avg       1.00      0.94      0.96    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [86]:
print(classification_report(y_test, y_dtc_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.49      0.66      1037
         DoSattack       1.00      1.00      1.00        63
              scan       1.00      1.00      1.00       218
  malitiousControl       1.00      1.00      1.00       156
malitiousOperation       1.00      1.00      1.00       381
            spying       1.00      1.00      1.00       134
       dataProbing       1.00      1.00      1.00        21
        wrongSetUp       0.99      1.00      1.00     86963

          accuracy                           0.99     88973
         macro avg       1.00      0.94      0.96     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Decision Tree Classifier

### For Training dataset

In [87]:
confusion_matrix(y_train, y_dtc_train_pred)

array([[  1490,      0,      0,      0,      0,      0,      0,   1473],
       [     0,    179,      0,      0,      0,      0,      0,      0],
       [     0,      0,    671,      0,      0,      0,      0,      0],
       [     0,      0,      0,    501,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1150,      0,      0,      0],
       [     0,      0,      0,      0,      0,    398,      0,      0],
       [     0,      0,      0,      0,      0,      0,    101,      0],
       [     0,      0,      0,      0,      0,      0,      0, 260955]],
      dtype=int64)

### For Testing dataset

In [88]:
confusion_matrix(y_test, y_dtc_test_pred)

array([[  510,     0,     0,     0,     0,     0,     0,   527],
       [    0,    63,     0,     0,     0,     0,     0,     0],
       [    0,     0,   218,     0,     0,     0,     0,     0],
       [    0,     0,     0,   156,     0,     0,     0,     0],
       [    0,     0,     0,     0,   381,     0,     0,     0],
       [    0,     0,     0,     0,     0,   134,     0,     0],
       [    0,     0,     0,     0,     0,     0,    21,     0],
       [    0,     0,     0,     0,     0,     0,     0, 86963]],
      dtype=int64)

## Random Forest Classifier

### For Training Dataset

In [89]:
print(classification_report(y_train, y_rfc_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.50      0.67      2963
         DoSattack       1.00      1.00      1.00       179
              scan       1.00      1.00      1.00       671
  malitiousControl       1.00      1.00      1.00       501
malitiousOperation       1.00      1.00      1.00      1150
            spying       1.00      1.00      1.00       398
       dataProbing       1.00      1.00      1.00       101
        wrongSetUp       0.99      1.00      1.00    260955

          accuracy                           0.99    266918
         macro avg       1.00      0.94      0.96    266918
      weighted avg       0.99      0.99      0.99    266918



### For Testing Dataset

In [91]:
print(classification_report(y_test, y_rfc_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       1.00      0.49      0.66      1037
         DoSattack       1.00      1.00      1.00        63
              scan       1.00      1.00      1.00       218
  malitiousControl       1.00      1.00      1.00       156
malitiousOperation       1.00      1.00      1.00       381
            spying       1.00      1.00      1.00       134
       dataProbing       1.00      1.00      1.00        21
        wrongSetUp       0.99      1.00      1.00     86963

          accuracy                           0.99     88973
         macro avg       1.00      0.94      0.96     88973
      weighted avg       0.99      0.99      0.99     88973



## Confusion Matrix for Random Forest Classifier

### For Training dataset

In [92]:
confusion_matrix(y_train, y_rfc_train_pred)

array([[  1490,      0,      0,      0,      0,      0,      0,   1473],
       [     0,    179,      0,      0,      0,      0,      0,      0],
       [     0,      0,    671,      0,      0,      0,      0,      0],
       [     0,      0,      0,    501,      0,      0,      0,      0],
       [     0,      0,      0,      0,   1150,      0,      0,      0],
       [     0,      0,      0,      0,      0,    398,      0,      0],
       [     0,      0,      0,      0,      0,      0,    101,      0],
       [     0,      0,      0,      0,      0,      0,      0, 260955]],
      dtype=int64)

### For Testing dataset

In [93]:
confusion_matrix(y_test, y_rfc_test_pred)

array([[  510,     0,     0,     0,     0,     0,     0,   527],
       [    0,    63,     0,     0,     0,     0,     0,     0],
       [    0,     0,   218,     0,     0,     0,     0,     0],
       [    0,     0,     0,   156,     0,     0,     0,     0],
       [    0,     0,     0,     0,   381,     0,     0,     0],
       [    0,     0,     0,     0,     0,   134,     0,     0],
       [    0,     0,     0,     0,     0,     0,    21,     0],
       [    0,     0,     0,     0,     0,     0,     0, 86963]],
      dtype=int64)

## Naive Bayes

### For Training Dataset

In [94]:
print(classification_report(y_train, y_nb_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.34      1.00      0.50      2963
         DoSattack       0.04      0.84      0.07       179
              scan       0.19      0.93      0.31       671
  malitiousControl       0.67      1.00      0.81       501
malitiousOperation       1.00      0.13      0.23      1150
            spying       0.01      0.93      0.01       398
       dataProbing       1.00      1.00      1.00       101
        wrongSetUp       1.00      0.75      0.86    260955

          accuracy                           0.75    266918
         macro avg       0.53      0.82      0.47    266918
      weighted avg       0.99      0.75      0.85    266918



### For Testing Dataset

In [95]:
print(classification_report(y_test, y_nb_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.34      1.00      0.51      1037
         DoSattack       0.04      0.79      0.08        63
              scan       0.19      0.91      0.31       218
  malitiousControl       0.63      1.00      0.78       156
malitiousOperation       1.00      0.10      0.19       381
            spying       0.01      0.96      0.01       134
       dataProbing       1.00      1.00      1.00        21
        wrongSetUp       1.00      0.75      0.86     86963

          accuracy                           0.75     88973
         macro avg       0.53      0.81      0.47     88973
      weighted avg       0.99      0.75      0.85     88973



## Confusion Matrix for Naive Bayes

### For Training dataset

In [96]:
confusion_matrix(y_train, y_nb_train_pred)

array([[  2963,      0,      0,      0,      0,      0,      0,      0],
       [     0,    150,      0,      0,      0,      0,      0,     29],
       [     0,      0,    622,      0,      0,      6,      0,     43],
       [     0,      0,      0,    501,      0,      0,      0,      0],
       [     7,      0,      0,      0,    146,    635,      0,    362],
       [     0,      0,     29,      0,      0,    369,      0,      0],
       [     0,      0,      0,      0,      0,      0,    101,      0],
       [  5851,   3770,   2644,    242,      0,  52397,      0, 196051]],
      dtype=int64)

### For Testing dataset

In [97]:
confusion_matrix(y_test, y_nb_test_pred)

array([[ 1037,     0,     0,     0,     0,     0,     0,     0],
       [    0,    50,     0,     0,     0,     0,     0,    13],
       [    0,     0,   198,     0,     0,     3,     0,    17],
       [    0,     0,     0,   156,     0,     0,     0,     0],
       [    4,     0,     0,     0,    40,   232,     0,   105],
       [    0,     0,     6,     0,     0,   128,     0,     0],
       [    0,     0,     0,     0,     0,     0,    21,     0],
       [ 1982,  1181,   850,    90,     0, 17497,     0, 65363]],
      dtype=int64)

## Support Vector Machine Classifier

### For Training Dataset

In [98]:
print(classification_report(y_train, y_svc_train_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.94      0.50      0.66      2963
         DoSattack       0.00      0.00      0.00       179
              scan       0.00      0.00      0.00       671
  malitiousControl       0.99      0.73      0.84       501
malitiousOperation       0.00      0.00      0.00      1150
            spying       0.00      0.00      0.00       398
       dataProbing       0.00      0.00      0.00       101
        wrongSetUp       0.98      1.00      0.99    260955

          accuracy                           0.98    266918
         macro avg       0.37      0.28      0.31    266918
      weighted avg       0.97      0.98      0.98    266918



c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

### For Testing Dataset

In [99]:
print(classification_report(y_test, y_svc_test_pred, target_names=target_names))

                    precision    recall  f1-score   support

            Normal       0.96      0.49      0.65      1037
         DoSattack       0.00      0.00      0.00        63
              scan       0.00      0.00      0.00       218
  malitiousControl       0.99      0.74      0.85       156
malitiousOperation       0.00      0.00      0.00       381
            spying       0.00      0.00      0.00       134
       dataProbing       0.00      0.00      0.00        21
        wrongSetUp       0.98      1.00      0.99     86963

          accuracy                           0.98     88973
         macro avg       0.37      0.28      0.31     88973
      weighted avg       0.98      0.98      0.98     88973



c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

## Confusion Matrix for Support Vector Machine Classifier

### For Training dataset

In [100]:
confusion_matrix(y_train, y_svc_train_pred)

array([[  1490,      0,      0,      0,      0,      0,      0,   1473],
       [     0,      0,      0,      0,      0,      0,      0,    179],
       [     0,      0,      0,      0,      0,      0,      0,    671],
       [     0,      0,      0,    367,      0,      0,      0,    134],
       [     8,      0,      9,      0,      0,      0,      0,   1133],
       [     0,      0,      0,      0,      0,      0,      0,    398],
       [     0,      0,      0,      0,      0,      0,      0,    101],
       [    82,      0,      0,      2,      0,     13,      0, 260858]],
      dtype=int64)

### For Testing dataset

In [101]:
confusion_matrix(y_test, y_svc_test_pred)

array([[  510,     0,     0,     0,     0,     0,     0,   527],
       [    0,     0,     0,     0,     0,     0,     0,    63],
       [    0,     0,     0,     0,     0,     0,     0,   218],
       [    0,     0,     0,   116,     0,     0,     0,    40],
       [    3,     0,     1,     0,     0,     0,     0,   377],
       [    0,     0,     0,     0,     0,     0,     0,   134],
       [    0,     0,     0,     0,     0,     0,     0,    21],
       [   21,     0,     0,     1,     0,     2,     0, 86939]],
      dtype=int64)