In [4]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [3]:
data = pd.read_csv('mainSimulationAccessTraces.csv')
data

sourceID             sourceAddress       sourceType  \
0         lightcontrol2     /agent2/lightcontrol2  /lightControler   
1         lightcontrol3     /agent3/lightcontrol3  /lightControler   
2         lightcontrol1     /agent1/lightcontrol1  /lightControler   
3         lightcontrol4     /agent4/lightcontrol4  /lightControler   
4             movement4         /agent4/movement4  /movementSensor   
...                 ...                       ...              ...   
357947   lightcontrol23   /agent23/lightcontrol23  /lightControler   
357948  washingmachine2  /agent11/washingmachine2  /washingService   
357949  washingmachine2  /agent11/washingmachine2  /washingService   
357950   lightcontrol28   /agent28/lightcontrol28  /lightControler   
357951   lightcontrol28   /agent28/lightcontrol28  /lightControler   

         sourceLocation destinationServiceAddress destinationServiceType  \
0        BedroomParents     /agent2/lightcontrol2        /lightControler   
1           Dinningroom     /agent3/lightcontrol3        /lightControler   
2       BedroomChildren     /agent1/lightcontrol1        /lightControler   
3               Kitchen     /agent4/lightcontrol4        /lightControler   
4               Kitchen         /agent4/movement4        /movementSensor   
...                 ...                       ...                    ...   
357947           room_4         /agent23/tempin23         /sensorService   
357948       Watterroom         /agent11/battery4        /batteryService   
357949       Watterroom         /agent11/battery4        /batteryService   
357950           room_9       /agent28/movement28        /movementSensor   
357951           room_9         /agent28/tempin28         /sensorService   

       destinationLocation           accessedNodeAddress  accessedNodeType  \
0           BedroomParents         /agent2/lightcontrol2   /lightControler   
1              Dinningroom         /agent3/lightcontrol3   /lightControler   
2          BedroomChildren         /agent1/lightcontrol1   /lightControler   
3                  Kitchen         /agent4/lightcontrol4   /lightControler   
4                  Kitchen             /agent4/movement4   /movementSensor   
...                    ...                           ...               ...   
357947              room_4             /agent23/tempin23    /sensorService   
357948          Watterroom      /agent11/battery4/charge     /basic/number   
357949          Watterroom    /agent11/battery4/charging       /basic/text   
357950              room_9  /agent28/movement28/movement  /derived/boolean   
357951              room_9             /agent28/tempin28    /sensorService   

              operation    value      timestamp normality  
0       registerService     none  1520031600000    normal  
1       registerService     none  1520031603269    normal  
2       registerService     none  1520031603279    normal  
3       registerService     none  1520031603290    normal  
4       registerService     none  1520031603464    normal  
...                 ...      ...            ...       ...  
357947             read  20.3479  1520117997001    normal  
357948             read        9  1520117997339    normal  
357949             read     true  1520117997401    normal  
357950             read        0  1520117998907    normal  
357951             read  20.4131  1520117999000    normal  

[357952 rows x 13 columns]

In [7]:
data = pd.read_csv('dataset.csv')
data

0   1   2  3   4   5  6   7    8  9  10    11
0       7  21  30  2   3  29  2   3   57  5   1     0
1       7  32  70  2   4  67  2   4  132  5   1     0
2       7  15   1  2   2   0  2   2    0  5   1     0
3       7  33  77  2   7  72  2   7  142  5   1     0
4       7  55  78  3   7  73  3   7  144  6   1     0
...    ..  ..  .. ..  ..  .. ..  ..  ... ..  ..   ...
355886  7  25  46  2  15  45  4  15   90  7   0  8505
355887  7  82  14  7  10   8  0  10   16  0   0    22
355888  7  82  14  7  10   8  0  10   17  1   0     1
355889  7  30  62  2  20  60  3  20  120  3   0     0
355890  7  30  62  2  20  61  4  20  121  7   0  9156

[355891 rows x 12 columns]

In [8]:
y = data.iloc[:,0].values
x = data.iloc[:,1:].values
x,y

(array([[  21,   30,    2, ...,    5,    1,    0],
        [  32,   70,    2, ...,    5,    1,    0],
        [  15,    1,    2, ...,    5,    1,    0],
        ...,
        [  82,   14,    7, ...,    1,    0,    1],
        [  30,   62,    2, ...,    3,    0,    0],
        [  30,   62,    2, ...,    7,    0, 9156]], dtype=int64),
 array([7, 7, 7, ..., 7, 7, 7], dtype=int64))

In [12]:
y.shape

(355891,)

In [32]:
model = KMeans(n_clusters = 8)
model.fit(x)

KMeans()

In [33]:
model.labels_

array([0, 0, 0, ..., 0, 0, 5])

In [34]:
c = 0
d = {
    0:7,1:6,2:5,3:4,4:3,5:2,6:1,7:0
}
for i in range(len(model.labels_)):
    z = d[model.labels_[i]]
    if(z == y[i]):
        c+=1
c

228618

In [28]:
c= 0
for i in range(len(model.labels_)):
   
    if(model.labels_[i] == y[i]):
        c+=1
c

14427

In [16]:
c/355891

0.6412497084781577

In [17]:
from sklearn.mixture import GaussianMixture

In [18]:
gmm = GaussianMixture(n_components = 8)
gmm.fit(x)

GaussianMixture(n_components=8)

In [19]:
yp = gmm.predict(x)

In [21]:
c = 0
for i in range(len(yp)):
    a = d[yp[i]]
    if(a == y[i]):
        c+=1
c

220337

In [22]:
c/355891

0.6191137174022383